export default [
  {
    ignores: [
      'node_modules/**',
      'vendor/**',
      'dist/**',
      '.build/**',
      'test-results/**',
      'playwright-report/**',
    ],
  },
  {
    files: ['**/*.js', '**/*.mjs'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: Object.fromEntries(
        [
          'document',
          'DOMException',
          'Storage',
          'Response',
          'getComputedStyle',
          'ResizeObserver',
          'requestAnimationFrame',
          'cancelAnimationFrame',
          'innerWidth',
          'innerHeight',
          'console',
          'process',
          'Buffer',
          'global',
          'URLSearchParams',
          'TextDecoder',
          'btoa',
          'setInterval',
          'clearInterval',
          'performance',
          'AbortSignal',
          'DOMParser',
          'window',
          'navigator',
          'location',
          'localStorage',
          'crypto',
          'matchMedia',
          'Blob',
          'URL',
          'ClipboardItem',
          'FileReader',
          'File',
          'Image',
          'TextEncoder',
          'atob',
          'setTimeout',
          'clearTimeout',
          'structuredClone',
          'fetch',
          'AbortController',
        ].map((name) => [name, 'readonly']),
      ),
    },
    rules: {
      'no-undef': 'error',
      'no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
      eqeqeq: 'error',
      'no-unreachable': 'error',
      'no-duplicate-imports': 'error',
    },
  },
];
